# Generated by Django 4.1 on 2024-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_upload_prediction_upload_processed_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='descriptions/')),
                ('processed_description', models.TextField(blank=True, null=True)),
                ('description_vector', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
