# Generated by Django 4.1 on 2026-02-02 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
