# Generated by Django 4.1 on 2024-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_uploaddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='cosine_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
