# Generated by Django 4.1 on 2026-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_candidate_final_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
