# Generated by Django 4.1 on 2024-12-07 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0005_uploaddescription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDescriptionM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='descriptions/')),
                ('processed_description', models.TextField(blank=True, null=True)),
                ('description_vector', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadDescription',
        ),
    ]
