# Generated by Django 4.1 on 2024-12-08 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_alter_upload_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='job_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.uploaddescriptionm'),
        ),
    ]
