# Generated by Django 4.1 on 2024-12-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0009_alter_upload_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='job_description',
        ),
    ]
