# Generated by Django 4.1 on 2024-12-08 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0010_remove_upload_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddescriptionm',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
