# Generated by Django 4.1 on 2024-12-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0011_alter_uploaddescriptionm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='job_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.uploaddescriptionm'),
        ),
    ]
