# Generated by Django 4.1 on 2024-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0012_upload_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddescriptionm',
            name='descriptionA',
            field=models.CharField(default='None Available', max_length=100),
        ),
    ]
