# Generated by Django 5.1.3 on 2024-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0017_rename_jobseeker_jobseekerregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerregister',
            name='prediction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerregister',
            name='processed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerregister',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
