# Generated by Django 5.1.3 on 2024-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0018_jobseekerregister_cosine_similarity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
