# Generated by Django 5.1.3 on 2024-12-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0022_alter_job_job_foreignkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_foreignkey',
            new_name='user',
        ),
    ]
