# Generated by Django 4.1 on 2024-12-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0023_rename_job_foreignkey_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
        ),
    ]
