# Generated by Django 4.1 on 2024-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0024_remove_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description_file',
            field=models.FileField(blank=True, null=True, upload_to='description/'),
        ),
        migrations.AddField(
            model_name='job',
            name='processed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
