# Generated by Django 4.1 on 2024-12-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0025_job_description_vector_job_job_description_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_description',
        ),
    ]
