# Generated by Django 4.1 on 2024-12-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0026_remove_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregister',
            name='job_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.job'),
        ),
    ]
