# Generated by Django 4.1 on 2024-12-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0027_jobseekerregister_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
