# Generated by Django 4.1 on 2024-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0029_alter_jobseekerregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
