# Generated by Django 4.1 on 2024-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0031_alter_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
