# Generated by Django 4.1 on 2024-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0035_alter_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
