# Generated by Django 4.1 on 2024-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0037_alter_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
