# Generated by Django 4.1 on 2024-12-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0038_alter_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerregister',
            name='cosine_similarity_score',
        ),
    ]
