# Generated by Django 4.1 on 2025-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0040_jobseekerregister_cosine_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
