# Generated by Django 4.1 on 2025-07-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0043_alter_question_category_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selecteed_option',
            new_name='selected_option',
        ),
    ]
