# Generated by Django 4.1 on 2025-07-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0044_rename_selecteed_option_answer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregister',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
