# Generated by Django 4.1 on 2025-07-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0045_jobseekerregister_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerregister',
            old_name='profile_picture',
            new_name='profile_pics',
        ),
    ]
