# Generated by Django 4.1 on 2025-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0046_rename_profile_picture_jobseekerregister_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
