# Generated by Django 4.1 on 2025-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0047_alter_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_vecotr',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
