# Generated by Django 4.1 on 2025-10-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0048_question_reference_vecotr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reference_vecotr',
            new_name='reference_vector',
        ),
    ]
