# Generated by Django 4.1 on 2025-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0049_rename_reference_vecotr_question_reference_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
