# Generated by Django 4.1 on 2025-11-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0051_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicious', models.BooleanField(default=False)),
                ('flags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.candidate')),
            ],
        ),
    ]
