# Generated by Django 4.1 on 2025-11-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0052_candidatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Resume.candidate'),
        ),
    ]
