# Generated by Django 4.1 on 2025-12-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0053_alter_candidatelog_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerregister',
            name='skill_ner',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
