# Generated by Django 4.1 on 2025-12-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0055_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('data scientist', 'Data Science'), ('software developer', 'Software Developer'), ('cybersecurity specialist', 'Cybersecurity Specialist'), ('devops engineer', 'Devops engineer'), ('graphics engineer', 'Graphics engineer'), ('machine learning engineer', 'Machine Learning Engineer'), ('robotics engineer', 'Robotics Engineer')], max_length=30),
        ),
    ]
