# Generated by Django 4.1 on 2025-12-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0056_alter_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_snapshot', models.FileField(upload_to='applied_resumes/')),
                ('skill_ner_snapshot', models.JSONField(blank=True, null=True)),
                ('vector_snapshot', models.JSONField(blank=True, null=True)),
                ('processed_text_snapshot', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.jobseekerregister')),
            ],
        ),
    ]
