# Generated by Django 4.1 on 2025-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0057_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cosine_similarity_score',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
