# Generated by Django 4.1 on 2025-12-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0059_jobapplication_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
