# Generated by Django 4.1 on 2025-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0060_job_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
