# Generated by Django 4.1 on 2026-01-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=10, null=True)),
                ('written_answer', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.ManyToManyField(to='Resume.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='description/')),
                ('job_requirements', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('processed_description', models.TextField(blank=True, null=True)),
                ('description_vector', models.JSONField(blank=True, null=True)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('objective', 'Objective'), ('mcq', 'MCQ'), ('subjective', 'Subjective'), ('code', 'Code')], max_length=20)),
                ('difficulty', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20)),
                ('category', models.CharField(choices=[('data scientist', 'Data Science'), ('software developer', 'Software Developer'), ('cybersecurity specialist', 'Cybersecurity Specialist'), ('devops engineer', 'Devops engineer'), ('graphics engineer', 'Graphics engineer'), ('machine learning engineer', 'Machine Learning Engineer'), ('robotics engineer', 'Robotics Engineer')], max_length=30)),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=10, null=True)),
                ('test_cases', models.JSONField(blank=True, null=True)),
                ('reference_answer', models.TextField(blank=True, null=True)),
                ('reference_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_provider', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skills', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pics', models.ImageField(null=True, upload_to='profile_pics/')),
                ('processed_text', models.TextField(blank=True, null=True)),
                ('vector', models.JSONField(blank=True, null=True)),
                ('prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('cosine_similarity_score', models.TextField(default=0, max_length=100)),
                ('skill_ner', models.JSONField(blank=True, null=True)),
                ('job_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobProviderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_snapshot', models.FileField(upload_to='applied_resumes/')),
                ('skill_ner_snapshot', models.JSONField(blank=True, null=True)),
                ('vector_snapshot', models.JSONField(blank=True, null=True)),
                ('processed_text_snapshot', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cosine_similarity_score', models.TextField(default=0, max_length=100)),
                ('prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.jobseekerregister')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicious', models.BooleanField(default=False)),
                ('flags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Resume.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.job'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
