# Generated by Django 4.1 on 2026-04-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0004_candidate_final_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='test_taken',
            field=models.BooleanField(default=False),
        ),
    ]
