# Generated by Django 4.1 on 2026-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_candidate_test_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
