# Generated by Django 4.1 on 2026-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
