# Generated by Django 4.1 on 2026-06-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0007_alter_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AI / Machine Learning', 'AI / Machine Learning'), ('Backend Development', 'Backend Development'), ('Cybersecurity', 'Cybersecurity'), ('DevOps / Cloud Engineering', 'DevOps / Cloud Engineering'), ('Frontend Development', 'Frontend Development'), ('Mobile Development', 'Mobile Development'), ('QA / Test Engineering', 'QA / Test Engineering')], max_length=30),
        ),
        migrations.CreateModel(
            name='CandidateActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resume.candidate')),
            ],
        ),
    ]
