# Generated by Django 4.1 on 2026-06-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0008_alter_question_category_candidateactiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='test_link_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CandidateActionToken',
        ),
    ]
